server:
  port: 8080
  ssl:  # 配置 https 证书 只能调用https接口
    key-store: classpath:keystore.p12
    key-store-password: emilia
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: tianpengfei123
  jpa:
    show-sql: true  # 默认false，在日志里显示执行的sql语句
    open-in-view: false
    hibernate:
      ddl-auto: update  # 指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# 打印的日志保存到该路径下
logging:
  file:
    name: /home/log/logInfo.log
